server.port=8080
spring.application.name=bookshop-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ishanchinthaka0822:sRD0rHRafotTuDyW@pahana01.0tcop35.mongodb.net/
spring.data.mongodb.database=bookshop

# JWT Configuration
bookshop.app.jwtSecret=bookshopSecretKey2024SuperSecureLongKeyForJWTTokenGenerationAndValidationPurposes
bookshop.app.jwtExpirationMs=86400000

# CORS Configuration
bookshop.app.frontend.url=http://localhost:5173

# Logging
logging.level.com.bookshop=DEBUG
logging.level.org.springframework.security=DEBUG
